### ISSUE TITLE
hmmlearn.py error

### ISSUE THREAD

**Issue by sukalyanM** [srinidhinandakumar/hidden_markov_models#1]
Hi Srinidhi,
In hmmlearn.py where to keep these files.
filename1 = sys.argv[1]
    # filename1 = "data/zh_train_tagged.txt"
    filename2 = "hmmmodel.txt"
    filename3 = "hmmmodel.json"
    """
    filename1 = "test/en_train_dev_tagged.txt"
    filename2 = "test/results/hmmmodel_en.txt"
    filename3 = "test/results/hmmmodel_en.json"
    """
I stuck here...Plz help

**Comment by srinidhinandakumar** [comment]
Hi @sukalyanM,
filename1 represents your training data and is a sys argument - so you need to give the path to the file with training data while running hmmlearn.py
filename2 and filename3 are the results that will be saved in the same directory as hmmlearn.py 

Also, the sample data I've used to train can be found here:
`data/zh_train_tagged.txt`

The sample filenames are mentioned inside the commented portion here
```python 
"""
filename1 = "test/en_train_dev_tagged.txt"

filename2 = "test/results/hmmmodel_en.txt"

filename3 = "test/results/hmmmodel_en.json"
"""
